### ISSUE TITLE
Repository Structure

### ISSUE THREAD

**Issue by luandy64** [kdamodaran1/tap-okta#1]
Currently, the repository looks like:
```
~/tap-okta
├── README.md
├── config
│   ├── config.json
│   └── target_config.json
├── schema
│   ├── application_groups.json
│   ├── application_users.json
│   ├── applications.json
│   ├── group_users.json
│   ├── groups.json
│   └── users.json
└── tap-okta.py
```

This is not the recommended Python Packaging way to do this. Moreover, it
breaks the composability aspect of how Singer works because we can't
install a tap that has this structure.

However I expect the repository to look like:
```
~/tap-okta
├── README.md
├── tap_okta
│   ├── __init__.py
│   └── schemas
│       ├── application_groups.json
│       ├── application_users.json
│       ├── applications.json
│       ├── group_users.json
│       ├── groups.json
│       └── users.json
├── sample_config.json
├── setup.cfg
└── setup.py
```

- The `README` file at the root of the directory is great
- I think the `schema` folder should be renamed `schemas` and moved under
  the new `tap_okta` folder
  - This keeps it consistent with other taps
- The `tap-okta.py` file was moved into the `tap_okta` folder and renamed
  `__init__.py`.
- We don't need a folder for config files because the there should only be
  a config for the tap. The tap does not need to know anything about a
  target. I also renamed it `sample_config.json` to indicate to users that
  this is an example of what a config file should look like.
- `setup.cfg` is a file that contains some config options for the
  `setup.py` file.
- `setup.py` has a function with keyword arguments that specify how the
  project should be set up

**Comment by kdamodaran1** [comment]
Modified the Repsoirory structure

**Comment by KAllan357** [comment]
The setup.py and file structure in the tap is still incorrect.

* There's a missing `)` at the end which causes the setup.py to be malformed.
* The directory structure @luandy64  pointed out is incorrect. Namely, the directory should be `tap_okta` not `tap-okta` 
* There needs to be a MANIFEST.in file at the root directory. This provides a path to packaging the actual schema.json files with the rest of the distribution. See [here](https://github.com/singer-io/tap-shopify/blob/master/MANIFEST.in) for an example.

**Comment by kdamodaran1** [comment]
Added ) to the Setup.py file
changed the directory from tap-okta to tap_okta
Added MANIFEST.in file in the root directory

**Comment by kdamodaran1** [comment]
@KAllan357 
Added ) to the Setup.py file
changed the directory from tap-okta to tap_okta
Added MANIFEST.in file in the root directory

**Comment by luandy64** [comment]
See [the repo in Singer-io](https://github.com/singer-io/tap-okta) for what I am looking for:
- Change the repository name from `tap_okta` to `tap-okta`
- After making the above change, change the folder called `kdamodaran1/tap-okta/tap-okta` to `kdamodaran1/tap-okta/tap_okta`

**Comment by kdamodaran1** [comment]
@luandy64 Changed the repository name and the folder name

**Comment by kdamodaran1** [comment]
The repository folder structure has been modified. Please review and close this issue
