### ISSUE TITLE
`tap-okta.py`

### ISSUE THREAD

**Issue by luandy64** [kdamodaran1/tap-okta#3]
- `main()`
  - In `python` you don't have to separate the declaration step and the
    initialization step of a variable. So it's a code smell that `args`
    and `schema` are declared to just be the global dictionaries you set
    up at the start of the file.
    - It's also pointless that `args` is setup as a dictionary and then
      you override it with `singer.utils.parse_args()`
  - Similarly, `schema` is initialized as `{}` and then overridden by
    `load_schemas()`
  - `header_payload()` is called, but the return value isn't stored. This
    function only works because the `global header` variable is modified. 
  - Why not pass the config to `load_data()` so that it can pass it to
    `url_pagination()`? If it's because you like using global variables,
    then why pass `args.config` to `header_payload()`? Technically
    `header_payload()` has access to `args`.
    - I prefer consistency and not using global variables a lot of
      - `LOGGER`, `REQUIRED_CONFIG_KEYS`, and `schema_list` are fine as
        globals though
- `load_schemas()`
  - Singer almost just assumes that people will run this in a Linux
    environment. So the backslash in the path here will fail.
  - Another note about consistency: How come `main()` named variables it
    wanted to use as `global`, but here the global `schemas` is not
    declared as `global schema` first?
    - I would prefer that `schemas` is declared as a local variable here
- `header_payload()`
  - `main()` doesn't make any requests at all. So it's strange to me that
    the headers are set up in `main` and not in `url_pagination()`
- `load_data()`
  - Consistency: Why is `schema_list` used here but not declared as
    `global schema_list` first?
    - I would prefer `schema_list` is declared as a local variable here
  - If the intent here is that all 3 streams always sync every time the
    tap runs, why use the `for` loop?
    - You could just call `url_pagination()` three times with different
      parameters
- `url_pagination()`
  - Why override the `python` built-in keyword `next`?
  - `data = json.loads(response.text)`: I don't know what `response.text`
    looks like here, but would `response.json()` work here? 
  - This entire `while (next or first)` loop is poorly designed. 
    - When you first enter the function, you can set `next_url` equal to
      `p_url`. Then the loop can check `while(next_url):`. Then you make
      the request to `next_url` and parse the header links. Then the `for
      linkobj in response_links` can use `next_url = linkobj.get('url')`.
      This eliminates the complicated `next = True` and `first = False`
      logic and when `get('url')` fails, it defaults to `None`. That way
      on the next check in `while(next_url)`, `None` makes the loop fail. 
  - Consistency: Why let `groups_for_user` and `lst_urs_assign_app` be
    globals if they are not declared `global groups_for_user` and 
    `global lst_urs_assign_app`?
    - I prefer these two variables to be declared locally to this
      function.

**Comment by kdamodaran1** [comment]
Code has been updated based on the review comments

**Comment by luandy64** [comment]
A lot of code has changed since this issue was opened, so I'm closing this
